<?php
	//application details
		$apps[$x]['name'] = "XML CDR";
		$apps[$x]['guid'] = '4A085C51-7635-FF03-F67B-86E834422848';
		$apps[$x]['category'] = 'PBX';
		$apps[$x]['subcategory'] = '';
		$apps[$x]['version'] = '';
		$apps[$x]['license'] = 'Mozilla Public License 1.1';
		$apps[$x]['url'] = 'http://www.fusionpbx.com';
		$apps[$x]['description']['en'] = 'Call Detail Records with all information about the call.';

	//menu details
		$apps[$x]['menu'][0]['title']['en'] = 'Apps';
		$apps[$x]['menu'][0]['guid'] = 'FD29E39C-C936-F5FC-8E2B-611681B266B5';
		$apps[$x]['menu'][0]['parent_guid'] = '';
		$apps[$x]['menu'][0]['category'] = 'internal';
		$apps[$x]['menu'][0]['path'] = '/mod/xml_cdr/v_xml_cdr.php';
		$apps[$x]['menu'][0]['order'] = '3';
		$apps[$x]['menu'][0]['groups'][] = 'user';
		$apps[$x]['menu'][0]['groups'][] = 'admin';
		$apps[$x]['menu'][0]['groups'][] = 'superadmin';
	
		$apps[$x]['menu'][1]['title']['en'] = 'Call Detail Records';
		$apps[$x]['menu'][1]['guid'] = '8F80E71A-31A5-6432-47A0-7F5A7B271F05';
		$apps[$x]['menu'][1]['parent_guid'] = 'FD29E39C-C936-F5FC-8E2B-611681B266B5';
		$apps[$x]['menu'][1]['category'] = 'internal';
		$apps[$x]['menu'][1]['path'] = '/mod/xml_cdr/v_xml_cdr.php';
		$apps[$x]['menu'][1]['groups'][] = 'user';
		$apps[$x]['menu'][1]['groups'][] = 'admin';
		$apps[$x]['menu'][1]['groups'][] = 'superadmin';

	//permission details
		$apps[$x]['permissions'][0]['name'] = 'xml_cdr_view';
		$apps[$x]['permissions'][0]['groups'][] = 'user';
		$apps[$x]['permissions'][0]['groups'][] = 'admin';
		$apps[$x]['permissions'][0]['groups'][] = 'superadmin';

	//schema details
		$y = 0;
		$apps[$x]['db'][0]['table'] = 'v_xml_cdr';
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'xml_cdr_id';
		$apps[$x]['db'][0]['fields'][$y]['type']['pgsql'] = 'serial';
		$apps[$x]['db'][0]['fields'][$y]['type']['sqlite'] = 'integer PRIMARY KEY';
		$apps[$x]['db'][0]['fields'][$y]['type']['mysql'] = 'INT NOT NULL AUTO_INCREMENT PRIMARY KEY';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'v_id';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'numeric';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'domain_name';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'accountcode';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'uuid';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'direction';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'default_language';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'context';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'xml_cdr';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'caller_id_name';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'caller_id_number';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'destination_number';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'start_epoch';
		$apps[$x]['db'][0]['fields'][$y]['type']['pgsql'] = 'numeric';
		$apps[$x]['db'][0]['fields'][$y]['type']['sqlite'] = 'numeric';
		$apps[$x]['db'][0]['fields'][$y]['type']['mysql'] = 'bigint';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'start_stamp';
		$apps[$x]['db'][0]['fields'][$y]['type']['pgsql'] = 'timestamp';
		$apps[$x]['db'][0]['fields'][$y]['type']['sqlite'] = 'date';
		$apps[$x]['db'][0]['fields'][$y]['type']['mysql'] = 'timestamp';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'answer_stamp';
		$apps[$x]['db'][0]['fields'][$y]['type']['pgsql'] = 'timestamp';
		$apps[$x]['db'][0]['fields'][$y]['type']['sqlite'] = 'date';
		$apps[$x]['db'][0]['fields'][$y]['type']['mysql'] = 'timestamp';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'answer_epoch';
		$apps[$x]['db'][0]['fields'][$y]['type']['pgsql'] = 'numeric';
		$apps[$x]['db'][0]['fields'][$y]['type']['sqlite'] = 'numeric';
		$apps[$x]['db'][0]['fields'][$y]['type']['mysql'] = 'bigint';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'end_epoch';
		$apps[$x]['db'][0]['fields'][$y]['type']['pgsql'] = 'numeric';
		$apps[$x]['db'][0]['fields'][$y]['type']['sqlite'] = 'numeric';
		$apps[$x]['db'][0]['fields'][$y]['type']['mysql'] = 'bigint';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'end_stamp';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'duration';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'numeric';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'mduration';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'numeric';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'billsec';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'numeric';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'billmsec';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'numeric';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'bridge_uuid';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'read_codec';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'read_rate';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'write_codec';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'write_rate';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'remote_media_ip';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'network_addr';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'recording_file';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = 'Indicates if a recording was made. If a recording exists set this value to true.';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'leg';
		$apps[$x]['db'][0]['fields'][$y]['type']['pgsql'] = 'char(1)';
		$apps[$x]['db'][0]['fields'][$y]['type']['sqlite'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['type']['mysql'] = 'char(1)';
		$apps[$x]['db'][0]['fields'][$y]['description'] = 'The leg of the call a or b.';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'pdd_ms';
		$apps[$x]['db'][0]['fields'][$y]['type']['pgsql'] = 'numeric';
		$apps[$x]['db'][0]['fields'][$y]['type']['sqlite'] = 'numeric';
		$apps[$x]['db'][0]['fields'][$y]['type']['mysql'] = 'smallint';
		$apps[$x]['db'][0]['fields'][$y]['description'] = 'Post Dial Delay (PDD) in miliseconds. Divide by 1000 for seconds.';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'last_app';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = 'Save the last application in the leg.';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'last_arg';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = 'Save the last application data.';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'cc_side';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = 'Queue side is either member or agent';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'cc_member_uuid';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = 'Unique member identifier';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'cc_queue_joined_epoch';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = 'Epoch when caller joined the queue';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'cc_queue';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = 'Queue';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'cc_member_session_uuid';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = 'Unique session identifier';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'cc_agent';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = 'agent name';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'cc_agent_type';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = 'agent type';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'conference_name';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = 'conference name';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'conference_uuid';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = 'conference unique identifier';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'conference_member_id';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = 'conference member id';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'digits_dialed';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = 'digits dialed';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'hangup_cause';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'hangup_cause_q850';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'numeric';
		$apps[$x]['db'][0]['fields'][$y]['description'] = '';
		$y++;
		$apps[$x]['db'][0]['fields'][$y]['name'] = 'sip_hangup_disposition';
		$apps[$x]['db'][0]['fields'][$y]['type'] = 'text';
		$apps[$x]['db'][0]['fields'][$y]['description'] = 'Save who hung up or cancelled the leg.';

?>
